apiVersion: v1
kind: Service
metadata:
  name: link-shortener
  labels:
    app: link-shortener
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: link-shortener
